name: builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cp config.mk.template config.mk
    - name: make
      run: make
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ matrix.os }}
        path: hactool(?:.exe)?
